./color_your_life.sh
./i_am_full.sh
./never_gonna_lock.sh
#./pimp_my_bash.sh
./restart_to_an_other_world.sh
./the_wati_gang.sh
#./the_world_upside_down.sh
./wait_a_minute.sh
./who_are_you.sh
./who_lives_in_a_pineapple.sh
./you_cant_do_that.sh
./where_re_you_from.sh
./fail_stumper.sh